### ISSUE TITLE
What are the splits used in the paper?

### ISSUE THREAD

**Issue by vzhong** [allenai/natural-instructions-v1#4]
Hey @swarooprm , I am very interested in this work and would like to reproduce your results. Can you please share the exact splits used in the paper? I am confused about how some of these splits are obtained. For example it looks like some of the evaluation tasks have less than 1k examples:

```
>>> import json
>>> with open('data/raw/subtask048_multirc_question_generation.json') as f: data = json.load(f)
...
>>> len(data['Instances'])
677
```

However, the paper mentions that each task has 6.5k train, 0.5k validation, and 1k test examples. How do you obtain these splits (especially for test) in the case where the original dataset doesn't have enough examples?

**Comment by vzhong** [comment]
CC @danyaljj

**Comment by swarooprm** [comment]
Reiterating our older email conversation "In our dataset, a task can have a maximum of 6.5k instances, however there are tasks with fewer instances. We have capped the number of instances to 6.5k so that the imbalance in the number of instances across tasks is minimal. While training, we oversample tasks with fewer instances and keep the number of instances across tasks constant (6.5k).

In our latest version, the training split has 49 tasks and the evaluation split has 12 tasks.
We use all instances of the 49 tasks for training and evaluate on certain instances of the 12 evaluation tasks (we can not evaluate on all because of token size usage limitation associated with GPT3).

You can notice that, Indexes for the GPT3 experiment are uniformly distributed from 60 to the size of the instances.
The Evaluation set has 12 tasks, the rest 49 tasks are used for training BART"
Both training and eval tasks can be downloaded from:
https://instructions.apps.allenai.org/
